apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-replicator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    workload-type: infra
spec:
  project: infra

  source:
    repoURL: https://helm.mittwald.de
    targetRevision: 2.12.3
    chart: kubernetes-replicator
  destination:
    namespace: kubernetes-replicator
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
