apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    workload-type: infra
spec:
  project: infra

  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp
    targetRevision: 0.40.0
    chart: headlamp
    helm:
      values: |
				env:
					- name: OIDC_CLIENT_ID
						valueFrom:
							secretKeyRef:
								name: headlamp-oidc
								key: client-id
					- name: OIDC_CLIENT_SECRET
						valueFrom:
							secretKeyRef:
								name: headlamp-oidc
								key: client-secret
					- name: OIDC_ISSUER_URL
						valueFrom:
							secretKeyRef:
								name: headlamp-oidc
								key: issuer-url
        config:
          oidc:
            scopes: "openid email profile groups"
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
