apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    workload-type: infra
spec:
  project: infra

  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp
    targetRevision: 0.40.0
    chart: headlamp
    helm:
      values: |
        config:
          oidc:
            secret:
              create: false
            externalSecret:
              enabled: true
              name: headlamp-oidc
            scopes: "openid email profile groups"
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
