apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    workload-type: infra
spec:
  project: infra

  source:
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.27.1
    chart: chart-name

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  info:
    - name: 'Example:'
      value: 'https://example.com'

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
