apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
type: Opaque
stringData:
  secret_key: "0PjlG9pw1Imb4oyy6YRFvwncGxhbHltSVJqcq1eVvb1gnUw2uxnjPrLq+rz6wLAnvUkUqXK4mSAemtZ6"
  bootstrap-password: "admin"
  bootstrap-email: "admin@example.com"
