apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-store
  namespace: tailscale
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "tailscale"       # le KV mount créé par OpenTofu
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "role-tailscale"          # créé par OpenTofu
          serviceAccountRef:
            name: "sa-vault-tailscale"    # le SA ci-dessus
