apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: authelia-secrets        # nom du Secret Kubernetes créé
    creationPolicy: Owner
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: authelia/config      # chemin dans le KV mount "authelia"
        property: jwt_secret

    - secretKey: session_secret
      remoteRef:
        key: authelia/config
        property: session_secret

    - secretKey: storage.encryption.key
      remoteRef:
        key: authelia/config
        property: storage_encryption_key

    - secretKey: session.encryption.key
      remoteRef:
        key: authelia/config
        property: session_encryption_key

    - secretKey: oidc_hmac_secret
      remoteRef:
        key: authelia/config
        property: oidc_hmac_secret

    - secretKey: oidc_private_key
      remoteRef:
        key: authelia/config
        property: oidc_private_key

    - secretKey: headlamp_client_secret
      remoteRef:
        key: authelia/config
        property: headlamp_client_secret

    - secretKey: headlamp_client_secret_hash
      remoteRef:
        key: authelia/config
        property: headlamp_client_secret_hash

    - secretKey: argocd_client_secret
      remoteRef:
        key: authelia/config
        property: argocd_client_secret

    - secretKey: argocd_client_secret_hash
      remoteRef:
        key: authelia/config
        property: argocd_client_secret_hash

    - secretKey: openbao_client_secret
      remoteRef:
        key: authelia/config
        property: openbao_client_secret

    - secretKey: openbao_client_secret_hash
      remoteRef:
        key: authelia/config
        property: openbao_client_secret_hash
