apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
  namespace: miniflux
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: miniflux-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: miniflux/config
        property: username
    - secretKey: password
      remoteRef:
        key: miniflux/config
        property: password
    - secretKey: oidc-client-secret
      remoteRef:
        key: miniflux/config
        property: oidc-client-secret
    - secretKey: oidc-client-id
      remoteRef:
        key: miniflux/config
        property: oidc-client-id
