---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
  namespace: domotic
data:
  configuration.yaml: |
    homeassistant: false
    permit_join: false
    mqtt:
      base_topic: zigbee2mqtt
      server: mqtt://mosquitto:1883
    serial:
      port: /dev/ttyUSB0
      adapter: ember
    frontend:
      enabled: true
      port: 8080
    advanced:
      log_level: info
    devices:
      '0xa4c138b9ef30ac87':
        friendly_name: ih-node-3
      '0xa4c13862d47eb4ed':
        friendly_name: Albert
      '0xa4c13808c560ce1a':
        friendly_name: ih-node-2
      '0xa4c138a0a6dd0917':
        friendly_name: ih-node-1
