apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microbin
  namespace: microbin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: microbin-admin
    creationPolicy: Owner
  data:
    - secretKey: MICROBIN_ADMIN_USERNAME
      remoteRef:
        key: microbin/config
        property: username

    - secretKey: MICROBIN_ADMIN_PASSWORD
      remoteRef:
        key: microbin/config
        property: password
