apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
 
  data:
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: observability/grafana/admin
        property: username
 
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: observability/grafana/admin
        property: password
