apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: grafana-oidc       # nom du Secret Kubernetes créé
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: observability/grafana-oidc
        property: client-id

    - secretKey: client-secret
      remoteRef:
        key: observability/grafana-oidc
        property: client-secret
