apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: authentik-secrets        # nom du Secret Kubernetes créé
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik/config      # chemin dans le KV mount "authentik"
        property: secret_key

    - secretKey: bootstrap-email
      remoteRef:
        key: authentik/config
        property: bootstrap-email

    - secretKey: bootstrap-password
      remoteRef:
        key: authentik/config
        property: bootstrap-password
