apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-store
  namespace: cloudflared
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "cloudflared"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "role-cloudflared"
          serviceAccountRef:
            name: "sa-vault-cloudflared"
