apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra

  source:
    repoURL: https://twin.github.io/helm-charts
    chart: gatus
    targetRevision: 1.5.0

    helm:
      values: |
        securityContext:
          capabilities:
            add:
              - NET_RAW
              - CAP_NET_RAW
        env:
          GATUS_LOG_LEVEL: "DEBUG"
          DB_HOST:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: host
          DB_PORT:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: port
          DB_NAME:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: dbname
          DB_USER:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: username
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: password

        config:
          storage:
            type: postgres
            path: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require"
          endpoints:
            - name: Zigbee2MQTT
              group: apps
              url: "https://zigbee2mqtt.tail7e39b9.ts.net"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
            - name: Microbin
              group: apps
              url: "https://bin.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
            - name: authelia
              group: infra
              url: "https://auth.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
            - name: argocd
              group: infra
              url: "https://argocd.tail7e39b9.ts.net"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
            - name: homepage
              group: infra
              url: "https://home.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
            - name: openbao
              group: infra
              url: "https://openbao.tail7e39b9.ts.net"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
            - name: grafana
              group: infra
              url: "https://grafana.tail7e39b9.ts.net"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
            - name: headlamp
              group: infra
              url: "https://headlamp.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
            - name: MASTER-1
              group: machines
              url: "tcp://192.168.1.17:22"
              interval: 30s
              conditions:
                - "[CONNECTED] == true"
                - "[RESPONSE_TIME] < 200"
            - name: WORKER-1
              group: machines
              url: "tcp://192.168.1.16:22"
              interval: 30s
              conditions:
                - "[CONNECTED] == true"
                - "[RESPONSE_TIME] < 200"
            - name: WORKER-2
              group: machines
              url: "tcp://192.168.1.15:22"
              interval: 30s
              conditions:
                - "[CONNECTED] == true"
                - "[RESPONSE_TIME] < 200"

        persistence:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: gatus

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
