apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra

  source:
    repoURL: https://twin.github.io/helm-charts
    chart: gatus
    targetRevision: 1.5.0

    helm:
      values: |
        env:
          MATRIX_ACCESS_TOKEN:
            valueFrom:
              secretKeyRef:
                name: gatus-matrix
                key: access-token
          DB_HOST:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: host
          DB_PORT:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: port
          DB_NAME:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: dbname
          DB_USER:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: username
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: gatus-cnpg-app
                key: password

        config:
          alerting:
            matrix:
              server-url: "https://matrix.issamhomelab.org"
              access-token: "${MATRIX_ACCESS_TOKEN}"
              internal-room-id: "!cztN3rw9IBQA6Xu2sw:matrix.issamhomelab.org"
          ui:
            default-sort-by: "group"
            header: ""
            title: "Status - Issamhomelab"
            logo: ""
            dashboard-subheading: "Endpoints status in realtime"
          storage:
            type: postgres
            path: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require"
          endpoints:
            - name: Zigbee2MQTT
              group: Apps
              url: "http://zigbee2mqtt.domotic.svc.cluster.local:8080"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<App> Zigbee2MQTT is down.."
                  send-on-resolved: true
            - name: Microbin
              group: Apps
              url: "https://bin.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<App> Microbin is down.."
                  send-on-resolved: true
            - name: Readeck
              group: Apps
              url: "https://read.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<App> Readeck is down.."
                  send-on-resolved: true
            - name: Miniflux
              group: Apps
              url: "https://rss.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<App> Miniflux is down.."
                  send-on-resolved: true
            - name: authelia
              group: Infra
              url: "https://auth.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<Infra> Authelia is down.."
                  send-on-resolved: true
            - name: argocd
              group: Infra
              url: "http://my-argo-cd-argocd-server.argocd.svc.cluster.local"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<Infra> ArgoCD is down.."
                  send-on-resolved: true
            - name: homepage
              group: Infra
              url: "https://home.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 401"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<Infra> Homepage is down.."
                  send-on-resolved: true
            - name: openbao
              group: Infra
              url: "http://openbao.openbao.svc.cluster.local:8200"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<Infra> Openbao is down.."
                  send-on-resolved: true
            - name: grafana
              group: Infra
              url: "http://grafana-service.observability.svc.cluster.local:3000"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<Infra> Grafana is down.."
                  send-on-resolved: true
            - name: headlamp
              group: Infra
              url: "https://headlamp.issamhomelab.org"
              interval: 30s
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] < 300"
              alerts:
                - type: matrix
                  description: "<Infra> Headlamp is down.."
                  send-on-resolved: true
            - name: MASTER-1
              group: Machines
              url: "tcp://192.168.1.17:22"
              interval: 30s
              conditions:
                - "[CONNECTED] == true"
                - "[RESPONSE_TIME] < 200"
              alerts:
                - type: matrix
                  description: "<Node> MASTER-1 is down.."
                  send-on-resolved: true
            - name: WORKER-1
              group: Machines
              url: "tcp://192.168.1.15:22"
              interval: 30s
              conditions:
                - "[CONNECTED] == true"
                - "[RESPONSE_TIME] < 200"
              alerts:
                - type: matrix
                  description: "<Node> WORKER-1 is down.."
                  send-on-resolved: true
            - name: WORKER-2
              group: Machines
              url: "tcp://192.168.1.16:22"
              interval: 30s
              conditions:
                - "[CONNECTED] == true"
                - "[RESPONSE_TIME] < 200"
              alerts:
                - type: matrix
                  description: "<Node> WORKER-2 is down.."
                  send-on-resolved: true
            - name: WORKER-3
              group: Machines
              url: "tcp://192.168.1.18:22"
              interval: 30s
              conditions:
                - "[CONNECTED] == true"
                - "[RESPONSE_TIME] < 200"
              alerts:
                - type: matrix
                  description: "<Node> WORKER-3 is down.."
                  send-on-resolved: true

        persistence:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: gatus

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
