apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: terraform-cnpg
  namespace: terraform
spec:
  instances: 2
  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: terraform
      owner: terraform
