apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-matrix
  namespace: gatus
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: gatus-matrix
    creationPolicy: Owner
  data:
    - secretKey: access-token
      remoteRef:
        key: gatus/matrix
        property: access-token
    - secretKey: status-room-id
      remoteRef:
        key: gatus/matrix
        property: status-room-id
