apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3-secret
  namespace: seaweedfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: seaweedfs-s3-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        seaweedfs_s3_config: |
          {
            "identities": [
              {
                "name": "loki",
                "credentials": [
                  {
                    "accessKey": "{{ .lokiAccessKey }}",
                    "secretKey": "{{ .lokiSecretKey }}"
                  }
                ],
                "actions": [
                  "Read",
                  "Write",
                  "List",
                  "Tagging"
                ]
              }
            ]
          }
 
  data:
    - secretKey: lokiAccessKey
      remoteRef:
        key: seaweedfs/s3-credentials
        property: lokiAccessKey
 
    - secretKey: lokiSecretKey
      remoteRef:
        key: seaweedfs/s3-credentials
        property: lokiSecretKey
