apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microbin-data
  namespace: microbin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: standard   # décommente et adapte si besoin (ex: "local-path", "nfs-client"...)

