apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-store
  namespace: cert-manager
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "cert-manager"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "role-cert-manager"
          serviceAccountRef:
            name: "sa-vault-cert-manager"
