apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readeck-data
  namespace: readeck
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: your-storage-class   # décommentez et adaptez si besoin
