apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap-secrets
  namespace: lldap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: lldap-credentials # nom du Secret Kubernetes créé
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        annotations:
          replicator.v1.mittwald.de/replication-allowed: "true"
          replicator.v1.mittwald.de/replicate-to: "authelia" 
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: lldap/credentials # chemin dans le KV mount "lldap"
        property: jwt-secret

    - secretKey: key-seed
      remoteRef:
        key: lldap/credentials # chemin dans le KV mount "lldap"
        property: key-seed

    - secretKey: base-dn
      remoteRef:
        key: lldap/credentials # chemin dans le KV mount "lldap"
        property: base-dn

    - secretKey: admin-user-password
      remoteRef:
        key: lldap/credentials # chemin dans le KV mount "lldap"
        property: admin-user-password
