apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zipline-secret
  namespace: zipline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: zipline-secret
    creationPolicy: Owner
  data:
    - secretKey: core-secret
      remoteRef:
        key: cloudflared/config
        property: core-secret
