apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: argocd-store
    kind: SecretStore
  target:
    name: argocd-oidc-secret      # nom du Secret Kubernetes créé
    creationPolicy: Owner
  data:
    - secretKey: argocd_client_secret
      remoteRef:
        key: argocd/config
        property: argocd_client_secret

    - secretKey: argocd_client_secret_hash
      remoteRef:
        key: argocd/config
        property: argocd_client_secret_hash
