apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: external-dns/cloudflare-credentials
        property: token
