apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-store
  namespace: external-dns
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "external-dns"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "role-external-dns"
          serviceAccountRef:
            name: "sa-vault-external-dns"
