apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 5c1e74f9-5915-46af-bdf7-4d6f3e0964ba
    credentials-file: /etc/cloudflared-credentials/credentials.json

    ingress:
      - service: https://traefik.traefik.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
          connectTimeout: 30s
          tlsTimeout: 30s
          tcpKeepAlive: 30s
          httpHostHeader: ""

    loglevel: info
    logfile: ""

    metrics: 0.0.0.0:2000
