apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: forgejo-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: forgejo/config
        property: oidc-client-secret
    - secretKey: key
      remoteRef:
        key: forgejo/config
        property: oidc-client-id
