apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readeck
  namespace: readeck
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: SecretStore
  target:
    name: readeck-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: readeck/config
        property: secret-key
