apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-cnpg
  namespace: authelia
spec:
  instances: 2
  storage:
    size: 10Gi

  bootstrap:
    initdb:
      database: authelia
      owner: authelia
